### ISSUE TITLE
Complete Pilot Briefing page

### ISSUE THREAD

**Issue by zid-wm** [zid-wm/zid-web#4]
**Is your feature request related to a problem? Please describe.**
The pilot briefing page is currently a placeholder.

**Describe the solution you'd like**
Add information about ZID airspace and airports.

**Describe alternatives you've considered**
Alternative could be removing the pilot briefing page, if it's found to be unnecessary.

**Additional context**
Some example pilot briefings can be found here: 
 - [https://clevelandcenter.org/briefing](https://clevelandcenter.org/briefing)
 - [https://www.nyartcc.org/prc](https://www.nyartcc.org/prc)
 - [http://www.zmaartcc.net/wp/pilots/airport-information](http://www.zmaartcc.net/wp/pilots/airport-information)

**Comment by nallen013** [comment]
Progress made on pilot briefing page with information about major airports in the airspace.

**Comment by nallen013** [comment]
Somehow I've completely lost the pilot briefing page I've written so far. Great.
